parameters:
    report.factory.class:                             Earls\RhinoReportBundle\Report\Factory\ReportFactory
    report.builder.class:                             Earls\RhinoReportBundle\Report\Definition\ReportBuilder
    report.definition.class:                          Earls\RhinoReportBundle\Report\Definition\ReportDefinition
    report.definition.builder.class:                  Earls\RhinoReportBundle\Report\Definition\ReportDefinitionBuilder

    report.template.generator.manager.class:          Earls\RhinoReportBundle\Report\Templating\DefaultTemplate\ReportTemplateGeneratorManager

    report.template.generator.html.class:             Earls\RhinoReportBundle\Report\Templating\DefaultTemplate\Generator\HtmlReportTemplateGenerator
    report.template.generator.html.template.filter:          EarlsRhinoReportBundle:Report/Body:filter.html.twig
    report.template.generator.html.template:          EarlsRhinoReportBundle:Report/Body:html.html.twig

    report_type:
        report:
            class:  Earls\RhinoReportBundle\Report\ReportObject\Report
            export: [ html ]
        table:
            class:  Earls\RhinoReportBundle\Module\Table\TableObject\Table
            export: [ csv, xls, html ]
        bar:
            class:  Earls\RhinoReportBundle\Module\Bar\BarObject\Bar
            export: [ html ]
            
services:
    report.factory:
        class:      %report.factory.class%
        arguments: ["@service_container"]

    report.builder:
        class:       %report.builder.class%

    report.definition.builder:
        class:      %report.definition.builder.class%
        arguments: ["%report.definition.class%"]

    report.template.generator.manager:
        class:    %report.template.generator.manager.class%
        arguments:
            - "@service_container"

    report.template.generator.html:
        class:    %report.template.generator.html.class%
        arguments:
            - "@templating"
            - "%report.template.generator.html.template%"
