parameters:
    report.factory.collection.class:                  Earls\RhinoReportBundle\Report\Factory\ReportObjectFactoryCollection
    report.factory.class:                             Earls\RhinoReportBundle\Report\Factory\ReportFactory
    report.definition.factory.manager.class:          Earls\RhinoReportBundle\Report\Factory\DefinitionFactoryManager
    report.builder.class:                             Earls\RhinoReportBundle\Report\Definition\ReportBuilder
    report.definition.class:                          Earls\RhinoReportBundle\Report\Definition\ReportDefinition
    report.definition.builder.class:                  Earls\RhinoReportBundle\Report\Definition\ReportDefinitionBuilder

    report.template.generator.manager.class:          Earls\RhinoReportBundle\Report\Templating\DefaultTemplate\ReportTemplateGeneratorManager

    report.template.default.generator.html.class:                      Earls\RhinoReportBundle\Report\Templating\DefaultTemplate\Generator\HtmlReportTemplateGenerator
    report.template.default.generator.html.template.filter:            EarlsRhinoReportBundle:Report/Body:filter.html.twig
    report.template.default.generator.html.template:                   EarlsRhinoReportBundle:Report/Body:html.html.twig

    report.DefaultTemplate:
        generator.service:
            html:       report.template.default.generator.html
        
    report_type:
        report:
            class:  Earls\RhinoReportBundle\Report\ReportObject\Report
            export: [ html ]
        table:
            class:  Earls\RhinoReportBundle\Module\Table\TableObject\Table
            export: [ csv, xls, html ]
        bar:
            class:  Earls\RhinoReportBundle\Module\Bar\BarObject\Bar
            export: [ html ]
            
services:
    report.factory:
        class:      %report.factory.class%
        arguments: ["@report.definition.factory.manager"]
        
    report.definition.factory.manager:
        class:  %report.definition.factory.manager.class%
        
    report.definition:
        class:      %report.definition.class%

    report.builder:
        class:       %report.builder.class%
        arguments:
            - "@lexik_form_filter.query_builder_updater"
            - "@form.factory"

    report.definition.builder:
        class:      %report.definition.builder.class%
        arguments: ["@report.definition"]

    report.template.generator.manager:
        class:    %report.template.generator.manager.class%
        arguments:
            - "@service_container"

    report.template.default.generator.html:
        class:    %report.template.default.generator.html.class%
        arguments:
            - "@templating"
            - "%report.template.default.generator.html.template%"
            - "%report.template.default.generator.html.template.filter%"
    
    report.listener.report_definition:
        class:      Earls\RhinoReportBundle\Report\Listener\RhnReportDefinitionListener
        arguments:  ["@report.factory"]
        tags:
            - { name: doctrine.event_listener, event: postLoad }