sudo: false
language:
    - php
php:
    - "5.5"
    
before_script:
    #coverage needs xdebug
    #- phpenv config-rm xdebug.ini
    - composer install
  
script:
    - composer run lint
    - composer run test_build
    - composer run test
    - composer run coverall
    
notifications:
    email:
        -  cifren@msn.com