sudo: false
language:
    - php
php:
    - "5.5"
    
services:
  - mysql
  
cache:
  directories:
    - $HOME/.composer/cache
    
before_script:
    #coverage needs xdebug
    #- phpenv config-rm xdebug.ini
    - composer update
  
script:
    - composer run lint
    - composer run test_func
    - composer run test
    - composer run coverall
    
notifications:
    email:
        -  cifren@msn.com