parameters:
    report.bar.factory.class:                               Earls\RhinoReportBundle\Module\Bar\Factory\BarFactory
    report.bar.definition.class:                            Earls\RhinoReportBundle\Module\Bar\Definition\BarDefinition
    report.bar.definition.builder.class:                    Earls\RhinoReportBundle\Module\Bar\Definition\BarDefinitionBuilder
    
    #templating
    #DefaultTemplate
    report.bar.template.default.generator.html.class:       Earls\RhinoReportBundle\Module\Bar\Templating\DefaultTemplate\Generator\HtmlBarTemplateGenerator
    
    report.bar.template.default.generator.html.template:    EarlsRhinoReportBundle:Bar/DefaultTemplate:html.html.twig

    bar.DefaultTemplate:
        generator.service:
            html:       report.bar.template.default.generator.html
            
services:
    report.bar.factory:
        class:      %report.bar.factory.class%
        tags:
            - { name: report.factory, alias: bar }
        
    report.bar.definition:
        class:      %report.bar.definition.class%
        scope:      prototype
        calls:
            - [setObjectFactory, ['@report.bar.factory']]
        
    report.bar.definition.builder:
        class:      %report.bar.definition.builder.class%
        scope:      prototype
        arguments: ["@report.bar.definition"]
        tags:
            - { name: report.definition.builder, alias: bar } 
            
    report.bar.template.default.generator.html:
        class:    %report.bar.template.default.generator.html.class%
        arguments:
            - "@templating"
            - %report.bar.template.default.generator.html.template%
            - 'report_unique_bar_default'