parameters:
    report.table.factory.class:                       Earls\RhinoReportBundle\Module\Table\Factory\TableFactory
    report.table.definition.class:                    Earls\RhinoReportBundle\Module\Table\Definition\TableDefinition
    report.table.definition.builder.class:            Earls\RhinoReportBundle\Module\Table\Definition\TableDefinitionBuilder
    report.table.retriever.class:                     Earls\RhinoReportBundle\Module\Table\Helper\TableRetrieverHelper
    report.table.manipulator.class:                   Earls\RhinoReportBundle\Module\Table\Util\DataManipulator
    report.table.extension.class:                     Earls\RhinoReportBundle\Module\Table\Extension\ReportExtension

    #Templating
    #Templating DefaultTemplate
    report.table.template.default.generator.html.class:       Earls\RhinoReportBundle\Module\Table\Templating\DefaultTemplate\Generator\HtmlTableTemplateGenerator
    report.table.template.default.generator.xls.class:        Earls\RhinoReportBundle\Module\Table\Templating\DefaultTemplate\Generator\XlsTableTemplateGenerator
    report.table.template.default.generator.csv.class:        Earls\RhinoReportBundle\Module\Table\Templating\DefaultTemplate\Generator\CsvTableTemplateGenerator    
    report.table.template.default.generator.html.template:    EarlsRhinoReportBundle:Table/DefaultTemplate:html.html.twig
    report.table.template.default.generator.xls.template:     EarlsRhinoReportBundle:Table/DefaultTemplate:xls.xml.twig
    report.table.template.default.xls.apply_formula.class:    Earls\RhinoReportBundle\Module\Table\Templating\DefaultTemplate\Util\XlsApplyFormula
    report.table.template.default.xls.simplifier.class:       Earls\RhinoReportBundle\Module\Table\Templating\DefaultTemplate\Simplifier\XlsReportSimplifier

    table.DefaultTemplate:
        generator.service:
            html:       report.table.template.default.generator.html
            xls:        report.table.template.default.generator.xls
            csv:        report.table.template.default.generator.csv
    
    #Templating DataTableTemplate
    table.DataTableTemplate:
        generator.service:
            html:       report.table.template.default.generator.html
            xls:        report.table.template.default.generator.xls
            csv:        report.table.template.default.generator.csv
    
            
services:
    report.table.factory:
        class:      %report.table.factory.class%
        arguments: ["@report.table.extension", "@report.table.retriever", "@report.table.manipulator"]

    report.table.definition.builder:
        class:      %report.table.definition.builder.class%
        arguments: ["%report.table.definition.class%"]
        tags:
            - { name: report.definition.builder, alias: table }        

    report.table.retriever:
        class:      %report.table.retriever.class%

    report.table.manipulator:
        class:      %report.table.manipulator.class%

    report.table.extension:
        class:      %report.table.extension.class%
#        public:     false
        arguments:
            - "@service_container"
            #Action on column
            - {}
            #GroupAction on column
            - {}
            #Action on row
            - {}
            #GroupAction on row
            - {}
            #Action on group
            - {}
            #GroupAction on Group
            - {}

    report.table.template.default.generator.html:
        class:    %report.table.template.default.generator.html.class%
        arguments:
            - "@templating"
            - %report.table.template.default.generator.html.template%

    report.table.template.default.generator.xls:
        class:    %report.table.template.default.generator.xls.class%
        arguments:
            - "@templating"
            - %report.table.template.default.generator.xls.template%
            - "@report.table.template.default.xls.simplifier"

    report.table.template.default.generator.csv:
        class:    %report.table.template.default.generator.csv.class%

    report.table.template.default.xls.apply_formula:
        class:    %report.table.template.default.xls.apply_formula.class%

    report.table.template.default.xls.simplifier:
        class:    %report.table.template.default.xls.simplifier.class%
        arguments:
            - "@report.table.template.default.xls.apply_formula"
            - true
            - "@report.table.factory"

#default Column - Action#
    report.table.action.column.basevalue:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\BaseValueAction
        tags:
            - { name: report.table.action.column, alias: basevalue }

    report.table.action.column.sprintf:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\SprintfAction
        tags:
            - { name: report.table.action.column, alias: sprintf }

    report.table.action.column.money_format:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\MoneyFormatAction
        tags:
            - { name: report.table.action.column, alias: money_format }

    report.table.action.column.date_format:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\DateFormatAction
        tags:
            - { name: report.table.action.column, alias: date_format }

    report.table.action.column.date_add:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\DateAddAction
        tags:
            - { name: report.table.action.column, alias: date_add }

    report.table.action.column.label_field:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\LabelFieldAction
        tags:
            - { name: report.table.action.column, alias: label_field }

    report.table.action.column.entity_field:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\EntityFieldAction
        arguments: ["@doctrine"]
        tags:
            - { name: report.table.action.column, alias: entity_field }

    report.table.action.column.round:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\RoundAction
        tags:
            - { name: report.table.action.column, alias: round }

    report.table.action.column.custom_php:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\CustomPhpAction
        tags:
            - { name: report.table.action.column, alias: custom_php }

    report.table.action.column.calculation:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\CalculationAction
        tags:
            - { name: report.table.action.column, alias: calculation }

    report.table.action.column.href:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\HrefAction
        arguments: ["@router"]
        tags:
            - { name: report.table.action.column, alias: href }

    report.table.action.column.basichref:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Column\BasicHrefAction
        arguments: ["@router"]
        tags:
            - { name: report.table.action.column, alias: basic_href }
#default Column - action#

#default Column - Group Action#
    report.table.group_action.column.sum:
        class: Earls\RhinoReportBundle\Module\Table\Actions\GroupAction\Column\SumGroupAction
        arguments: ["@report.table.retriever"]
        tags:
            - { name: report.table.group_action.column, alias: sum }
#default Column - Group Action#

#default Column - Group Action#
    report.table.group_action.column.empty_usage:
        class: Pp3\CustomReportBundle\Extension\Table\EmptyUsageAction
        arguments: ["@report.table.retriever"]
        tags:
            - { name: report.table.group_action.column, alias: empty_usage }
#default Column - Group Action#

#default Group - Action#
    report.table.action.group.order_by:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Group\OrderByAction
        arguments: ["@report.table.retriever"]
        tags:
            - { name: report.table.action.group, alias: orderBy }

    report.table.action.group.highlight_min:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Group\HighlightMinMaxAction
        arguments: ["@report.table.retriever", "min"]
        tags:
            - { name: report.table.action.group, alias: highlight_group_min }
    report.table.action.group.highlight_max:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Group\HighlightMinMaxAction
        arguments: ["@report.table.retriever", "max"]
        tags:
            - { name: report.table.action.group, alias: highlight_group_max }
#default Group - Action#

#default Row Action#
    report.table.group_action.column.highlight_min:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Row\HighlightMinMaxAction
        arguments: ["min"]
        tags:
            - { name: report.table.action.row, alias: highlight_min }

    report.table.group_action.column.highlight_max:
        class: Earls\RhinoReportBundle\Module\Table\Actions\ItemAction\Row\HighlightMinMaxAction
        arguments: ["max"]
        tags:
            - { name: report.table.action.row, alias: highlight_max }
#default Row Action#

#default Row - Group Action#
#default Row - Group Action#